### ISSUE TITLE
Linux Version

### ISSUE THREAD

**Issue by theallseingeye** [bettergram/bettergram#1]
Since the official telegram client supports linux have you considered publishing a linux version too? Ubuntu and Fedora

**Comment by gilmanov-ildar** [comment]
Yes, off course! We are going to publish Linux version soon.

**Comment by gilmanov-ildar** [comment]
@theallseingeye, also you can follow our public Trello board: [Bettergram Roadmap](https://trello.com/b/vpmaoijD/bettergram-roadmap)

**Comment by ArmeF97** [comment]
Linux version is out, we can close this 👍

**Comment by gilmanov-ildar** [comment]
Yes, now you can download it from https://bettergram.io/
