### ISSUE TITLE
Bettergram not opening on Ubuntu 16.04 LTS // GLIBC_2.25 not found

### ISSUE THREAD

**Issue by TheRodeo** [bettergram/bettergram#10]
### Steps to reproduce
Opening the bettergram file via command line throws up the following error

>  ./Bettergram 
./Bettergram: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by ./Bettergram)
./Bettergram: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by ./Bettergram)

Opening from GUI throws the following error

> Could not disaplay "Bettergram"
There is no application installed for "shared library" files.
Do you want to search for an application to open this file?

### Expected behaviour
Bettergram should open

### Actual behaviour
Bettergram throws error and doesn't open

### Configuration
**Operating system:** Ubuntu 16.04 LTS

**Version of Telegram Desktop:** 1.5.8

**Used theme**: Night Mode

<details><summary><b>Logs</b>:</summary>
$ ./Bettergram 
./Bettergram: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by ./Bettergram)
./Bettergram: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by ./Bettergram)
</details>

**Comment by gilmanov-ildar** [comment]
I published the latest Linux build on our Telegram group.
