### ISSUE TITLE
Cryptocurrency Prices Panel is broken

### ISSUE THREAD

**Issue by sxiii** [bettergram/bettergram#12]
### Steps to reproduce
1. Open Bettergram
2. Open any chat
3. Open PRICES panel on the right

### Expected behaviour
Prices should be shown in normal way

### Actual behaviour
Prices are messed up, and it even lacks the main cryptocurrency price -> BTC.

### Configuration
**Operating system:**
OS: Manjaro 18.0.2 Illyria
Kernel: x86_64 Linux 4.20.7-1-MANJARO
Uptime: 1h 25m
Packages: 1453
Shell: bash 5.0.0
Resolution: 1920x1080
DE: Xfce4
WM: Xfwm4
WM Theme: Adapta-Maia
GTK Theme: Adwaita-dark [GTK2]
Icon Theme: Papirus-Dark
Font: Noto Sans 10
CPU: AMD FX-7500 Radeon R7, 10 Compute Cores 4C+6G @ 4x 2.1GHz
GPU: AMD KAVERI (DRM 2.50.0, 4.20.7-1-MANJARO, LLVM 7.0.1)

**Version of Telegram Desktop:**
1.3.3

**Used theme**:
Dark

**Problem screenshot**:
https://imgur.com/SSkL6ec

**Comment by sxiii** [comment]
Probably the guys from LIVE COIN WATCH changed their website structure & the parser broke. I would recommend you, guys, to take crypto prices by API (let's say, CryptoCompare have perfect API or CoinMarketCap also have one) rather then parsing websites.

**Comment by gilmanov-ildar** [comment]
Please, use the latest version: 1.5.0. Here the link: [Bettergram Linux v1.5.0](https://drive.google.com/open?id=148RvggnYNa1GwyuR2BThdoKWC0p2nCwU)

**Comment by sxiii** [comment]
Thanks, that resolves the issue. Waiting for the tabs improvements also :)
