### ISSUE TITLE
chats/messages not current in Bettergram

### ISSUE THREAD

**Issue by hydrosloth** [bettergram/bettergram#2]
### Steps to reproduce
1.  unknown.  this is a regular thing since i've downloaded yesterday or the day before
2. 
3. 

Sometimes chats and messages are not current.   And sometimes ill respond to what looks like the most recent comment, and when i do, the comments flood in.   Other times they don't catch up and it just shows my post.

### Configuration
**Operating system:**   Windows 10

**Version of Telegram Desktop:**  1.3.14

![image](https://user-images.githubusercontent.com/34846719/45660411-a5a2c900-bac6-11e8-8fc4-37773c36e138.png)

**Comment by hydrosloth** [comment]
optic

**Comment by hydrosloth** [comment]
here is my log file also
[gggggggggggg.txt](https://github.com/bettergram/bettergram/files/2393155/gggggggggggg.txt)

**Comment by gilmanov-ildar** [comment]
@hydrosloth, what is your country?  Do you have censorship for Telegram there?

**Comment by hydrosloth** [comment]
usa,  no censorship

**Comment by gilmanov-ildar** [comment]
@hydrosloth, ok, it seems you had issues with network connections:

```
TCP Error: network - Host unreachable
HTTP Error: network error 99 - Host unreachable
```

Do you have such troubles with the original Telegram desktop application?

**Comment by gilmanov-ildar** [comment]
@hydrosloth, or maybe other sites are opening too long, or unreachable?

**Comment by hydrosloth** [comment]
hmm...   i've never had any problems like this with telegram, or opening any other sites..  I stream videos all the time without interuption..

**Comment by gilmanov-ildar** [comment]
John McCoffee, [24.09.18 22:39]
im thinking maybe the issue i had WAS because of my internet connection,  because i havn't had that issue since posting

So, I think we may close the issue

**Comment by AJolly** [comment]
I run into this issue frequently.
