### ISSUE TITLE
is this project dead?

### ISSUE THREAD

**Issue by ArmeF97** [bettergram/bettergram#20]

**Comment by stormyqq** [comment]
have the same question. it looks nice to kill like this.

**Comment by 360fun** [comment]
I love this project as well, so I investigated a bit and (sadly) found that the founder/CEO, Max Bloom, passed away few months ago...since then the development paused:
![image](https://user-images.githubusercontent.com/844090/62956639-98d04780-bdf3-11e9-81b9-1a0c4f957208.png)

Source: https://t.me/bettergramapp

**Comment by ArmeF97** [comment]
He passed away? Where did you find it?

**Comment by 360fun** [comment]
In the Telegram group:

> Source: https://t.me/bettergramapp

**Comment by ArmeF97** [comment]
You just linked the group but not the message, can you link the exact message?

**Comment by 360fun** [comment]
I thought was easy to find through the search function and also more respectful/transparent:
https://t.me/bettergramapp/8842

**Comment by ArmeF97** [comment]
Thank you for this news. Now it opens a new question, will development ever resume?

**Comment by 360fun** [comment]
Let's give them time and hope for the best! 🌳

**Comment by ArmeF97** [comment]
Let's hope. For now, I know Unigram does the job

**Comment by gilmanov-ildar** [comment]
Yes, it seems the project is dead.

**Comment by ArmeF97** [comment]
You are a collaborator, or a member of the bettergram team? Do you know more?

**Comment by gilmanov-ildar** [comment]
I was a member of Bettergram Team. Please, let's close the discussion.

**Comment by 360fun** [comment]
if I may suggest: somebody should write something on the website in order to make people stop asking and leave you in peace...like in the Telegram group. anyway, take care! 🙏

**Comment by ArmeF97** [comment]
Ok, I'll close but last question: do you have any other similar projects you are developing for? Or that you contribute in someway? Related to telegram

**Comment by gilmanov-ildar** [comment]
No

**Comment by ArmeF97** [comment]
Ok, thanks for your answers.
I'll close this issue.
