### ISSUE TITLE
Crash on macOs

### ISSUE THREAD

**Issue by neer1304** [bettergram/bettergram#21]
### Steps to reproduce
1. Open the app 
Sometimes also occur while using the app suddenly there is crash

### Expected behaviour
App should open

### Actual behaviour
App is getting crashed

### Configuration
MacOS Mojave Version 10.14.6, 16 GB Ram

**Version of Telegram Desktop:**
 1.6.2 
**Used theme**:

<details><summary><b>Logs</b>:</summary>
[Crashv1.6.2.log](https://github.com/bettergram/bettergram/files/3727405/Crashv1.6.2.log)

**Comment by gilmanov-ildar** [comment]
@neer1304, we stopped the development. Please use the official Telegram client.
