### ISSUE TITLE
Crash report in Linux.

### ISSUE THREAD

**Issue by kmvan** [bettergram/bettergram#23]
### Steps to reproduce
1. Run `bettergram` in command.
2. Wait a sesond.
3. Crashed.

### Expected behaviour
Shall not crash.

### Actual behaviour
Crash.

### Configuration
**Operating system:**
██████████████████  ████████   kmvan@kmvan-pc 
██████████████████  ████████   -------------- 
██████████████████  ████████   OS: Manjaro Linux x86_64 
██████████████████  ████████   Host: Aspire T5000 V1.15 
████████            ████████   Kernel: 5.4.12-1-MANJARO 
████████  ████████  ████████   Uptime: 22 hours, 30 mins 
████████  ████████  ████████   Packages: 1519 (pacman) 
████████  ████████  ████████   Shell: bash 5.0.11 
████████  ████████  ████████   Resolution: 1920x1080 
████████  ████████  ████████   DE: Xfce 
████████  ████████  ████████   WM: Xfwm4 
████████  ████████  ████████   WM Theme: QTStepDebianRed31p 
████████  ████████  ████████   Theme: Greybird [GTK2] 
████████  ████████  ████████   Icons: ubuntu-mono-dark [GTK2] 
                               Terminal: tilix 
                               CPU: Intel i7-6700HQ (8) @ 3.500GHz 
                               GPU: Intel HD Graphics 530 
                               GPU: NVIDIA GeForce GTX 950M 
                               Memory: 9081MiB / 15872MiB 

<details><summary><b>Logs</b>:</summary>
bettergram 

Qt: Session management error: Authentication Rejected, reason : None of the authentication protocols specified are supported and host-based authentication failed
bettergram[0xc9dab1]
bettergram[0xc9dfec]
bettergram(_ZN15google_breakpad16ExceptionHandler12GenerateDumpEPNS0_12CrashContextE+0x401)[0x1b70a01]
bettergram(_ZN15google_breakpad16ExceptionHandler13SignalHandlerEiP9siginfo_tPv+0xd8)[0x1b70d68]
/usr/lib/libpthread.so.0(+0x14930)[0x7fc8e7bd6930]
/usr/lib/libc.so.6(gsignal+0x145)[0x7fc8e78d6f25]
/usr/lib/libc.so.6(abort+0x12b)[0x7fc8e78c0897]
bettergram[0xd1320a]
bettergram[0x1096c2c]
bettergram[0xd162bc]
bettergram(_ZN10Bettergram17BettergramService24generateLastUpdateStringERK9QDateTimeb+0xbf)[0x156c58f]
bettergram(_ZN10Bettergram14RssChannelList13setLastUpdateERK9QDateTime+0x4c)[0x156d22c]
bettergram(_ZN10Bettergram14RssChannelList4loadEv+0xdf)[0x1574faf]
bettergram(_ZN10Bettergram17BettergramServiceC1EP7QObject+0x182)[0x1573e42]
bettergram(_ZN10Bettergram17BettergramService8instanceEv+0x37)[0x15748d7]
bettergram(_ZN4Core7Sandbox16closeApplicationEv+0x19a)[0xcd3a8a]
bettergram[0x2aadb8e]
bettergram[0x2a842bb]
bettergram(_ZN4Core7Sandbox5startEv+0x6b8)[0xccb398]
bettergram(_ZN4Core8Launcher18executeApplicationEv+0xb3)[0xcd3e73]
bettergram(_ZN4Core8Launcher4execEv+0x52)[0xcd3fc2]
bettergram(main+0x32)[0xa59ca2]
/usr/lib/libc.so.6(__libc_start_main+0xf3)[0x7fc8e78c2153]
bettergram(_start+0x29)[0xa7af89]
Aborted (core dumped)
</details>

###

**Comment by ildar-gilmanov** [comment]
Please note that the development is stopped. Do not create new Issues.

**Comment by kmvan** [comment]
Got it.
