### ISSUE TITLE
t.me Links Not Working

### ISSUE THREAD

**Issue by joesixpack** [bettergram/bettergram#3]
A t.me link to join a group or channel should normally launch the client and autojoin.  However, Bettergram-PC just launches the client without joining the group or channel.

**Comment by gilmanov-ildar** [comment]
@joesixpack, Is it your system is Windows? It is know issue and we have already fixed that at the dev code and you will see that at the next release

**Comment by gilmanov-ildar** [comment]
@joesixpack, thank you for your bug report! It is very important to give such feedback!

**Comment by joesixpack** [comment]
Cool, yeah I'm on Windows.

**Comment by joesixpack** [comment]
Any updates when this is going to be fixed?  It's problematic for joining private channels where the channel name is encrypted.

**Comment by joesixpack** [comment]
Seems to have been resolved.  I am not sure it was a Bettergram issue per se.  Theres conflicts between Bettergram and Telegram depending on the handler or what gets set in the OS or browser.  Hard to figure out and resetting it at the OS level and reinstalling seems best way to fix it.
